import CartContextProvider from "../components/context/CartContextProvider";
import Footer from "../components/share/Footer";
import Header from "../components/share/Header";
import "./globals.css";
export const metadata = {
  title: "mahan tasvir",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-[1441px] mx-auto">
    <CartContextProvider>
        <Header />
        {children}
        <Footer />
        </CartContextProvider>
      </body>
    </html>
  );
}
